version: '3.8'
services:
  birsdaymenu:
    build:
      dockerfile: Dockerfile
    container_name: birthday_frontend
    tty: true
    command: ['npm', 'run', 'dev']
    # stop_signal: SIGINT
    environment:
      - CHOKIDAR_USEPOLLING=true
      # 以下を書くなら、package.jsonのdevからhostname 0.0.0.0と--port 5555を削除する
      # - HOST=0.0.0.0
      # - PORT=5555
    volumes:
      - ./:/work
    ports:
      - 3000:3000
